# Generated by Django 5.1.5 on 2025-02-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoSite', '0003_remove_order_user_order_customer_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change_status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
